---

- name: Desplegar Django
  hosts: test_group
  remote_user: vagrant
  vars:
    - ubicacion_proyecto: /home/vagrant/app
    - bd: todolist
    - bd_usuario: user
    - bd_contra: "pass"
  tasks:
    - name: Instalar dependencias de sistema
      apt:
        name: ["apache2", "libapache2-mod-wsgi-py3", "git", "libffi-dev", "libxml2-dev", "libxslt1-dev", "zlib1g-dev", "libssl-dev", "build-essential", "autoconf", "python3", "python3-dev", "mysql-server", "mysql-client", "python3-dev", "libmysqlclient-dev", "python3-pip", "python-virtualenv"]
        state: present
        update_cache: yes
    - name: Descargar proyecto
      git:
        repo: https://github.com/Luis-MX/django-todo-app.git
        dest: "{{ ubicacion_proyecto }}"
    - name: Actualizar PIP
      become: True
      command:
        cmd: python3 -m pip install --upgrade pip
    - name: Instalar Pip Wheel
      command:
        cmd: python3 -m pip install -U wheel
    - name: Verificar presencia de pymysql
      pip:
        name: pymysql
        state: present
    - name: Crear Entorno virtual e instalar lista de requerimientos
      pip:
        virtualenv: "{{ ubicacion_proyecto }}/.env"
        virtualenv_python: python3
        name:
          - django==2.2
          - pymysql
          - mysqlclient
    - name: Cambiar tipo de autenticacion
      command:
        cmd: sudo mysql -u root -proot -e "use mysql;UPDATE user SET authentication_string=PASSWORD('root') WHERE User='root';UPDATE mysql.user SET plugin = 'mysql_native_password' WHERE User='root';flush privileges;"
    - name: crear base de datos
      become: yes
      mysql_db:
        login_user: root
        login_password: root
        name: "{{bd}}"
        state: present
    - name: Crear usuario
      become: yes
      mysql_user:
        login_user: root
        login_password: root
        name: "{{bd_usuario}}"
        password: "{{ bd_contra }}"
        priv: '{{bd}}.*:ALL'
        host: localhost
        state: present
    - name: Correr migraciones
      django_manage:
        app_path: "{{ ubicacion_proyecto }}"
        command: migrate
        virtualenv: "{{ ubicacion_proyecto }}/.env"
    - name: Configurar sitio de apache
      become: yes
      copy:
        src: deploy_files/apache-site.txt
        dest: /etc/apache2/sites-available/luis.conf
    - name: Habilitar sitio
      become: yes
      command:
        cmd: a2ensite luis
    - name: Recargar apache
      become: yes
      command:
        cmd: systemctl reload apache2.service

