---

- name: Servicio de despliegue para aplicación php
  hosts: test_group
  remote_user: vagrant
  vars:
    - ubicacion_proyecto: /var/www/html/test
    - bd: crud
    - bd_usuario: root
    - bd_contra: "root"
    - bd_contra_p: "root"
  tasks:
    - name: Instalando requisitos para el sistema
      apt:
        name: ["apache2","mysql-server","php","php-mysql","libapache2-mod-php","libmysqlclient-dev","mysql-client", "python3-pip"]      
        update_cache : yes
        state: present
    - name: Clonar proyecto
      git: 
        repo: https://github.com/Luis-MX/php-mysql-crud.git
        dest: "{{ubicacion_proyecto}}"
    - name: Estableciendo ServerName
      become: yes
      command:
        cmd: echo 'ServerName 0.0.0.0' | tee -a /etc/apache2/apache2.conf
    - name: Verificar presencia de pymysql
      pip:
        name: pymysql
        state: present
    - name: Cambiar tipo de autenticacion
      command:
        cmd: sudo mysql -u root -proot -e "use mysql;UPDATE user SET authentication_string=PASSWORD('root') WHERE User='root';UPDATE mysql.user SET plugin = 'mysql_native_password' WHERE User='root';flush privileges;"
    - name: crear base de datos
      become: yes
      mysql_db:
        login_user: root
        login_password: root
        name: "{{bd}}"
        state: present
    - name: Ejecutar script SQL
      command:
        chdir: "{{ubicacion_proyecto}}/database"
        cmd: sudo mysql -u root -proot -e "source crud.sql"
    - name: Recargar apache
      become: yes
      command:
        cmd: systemctl restart apache2.service

